// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TravelersMarkDbContext))]
    [Migration("20260708125143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Users.UserLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);

                    b.HasDiscriminator<string>("Provider").HasValue("UserLogin");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Aggregates.Users.GuestLogin", b =>
                {
                    b.HasBaseType("Domain.Aggregates.Users.UserLogin");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue("Guest");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.LocalLogin", b =>
                {
                    b.HasBaseType("Domain.Aggregates.Users.UserLogin");

                    b.HasDiscriminator().HasValue("Local");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.UserLogin", b =>
                {
                    b.HasOne("Domain.Aggregates.Users.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.LocalLogin", b =>
                {
                    b.OwnsOne("Domain.Aggregates.Users.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("LocalLoginId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Email");

                            b1.HasKey("LocalLoginId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("UserLogins");

                            b1.WithOwner()
                                .HasForeignKey("LocalLoginId");
                        });

                    b.OwnsOne("Domain.Aggregates.Users.ValueObjects.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("LocalLoginId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("LocalLoginId");

                            b1.ToTable("UserLogins");

                            b1.WithOwner()
                                .HasForeignKey("LocalLoginId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Navigation("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
